name: Set a new secret

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner of the repo to set the secret in'
        required: true
      repo-prefix:
        description: 'GitHub repo name prefix'
        required: true
      secret-key:
        description: 'Key to use for the secret'
        required: true
      secret-value:
        description: 'Value to use for the secret'
        required: true

jobs:
  secret:
    runs-on: ubuntu-latest
    environment: Manage Repositories

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build and run Go script
      run: |
        cmd="cd go/secret;go mod tidy;go run main.go"
        cmd="$cmd -owner=${{ github.event.inputs.owner }}"
        cmd="$cmd -repo-prefix=${{ github.event.inputs.repo-prefix }}"
        cmd="$cmd -secret-key=${{ github.event.inputs.secret-key }}"

        eval $cmd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PAT: ${{ secrets.GH_PAT }}
        SECRET_VALUE: ${{ github.event.inputs.secret-value }}
